# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-09 05:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeCreated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time Created')),
                ('nextLinkPosition', models.SmallIntegerField(default=0, verbose_name='Next Link Position')),
            ],
        ),
        migrations.CreateModel(
            name='DrawLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f', models.FileField(upload_to='', verbose_name='File')),
                ('linkPosition', models.SmallIntegerField(verbose_name='Link Position')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('numPlayers', models.SmallIntegerField(default=0, verbose_name='Number of Players')),
                ('started', models.BooleanField(default=False, verbose_name='Started?')),
                ('timeCreated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time Created')),
                ('roundNum', models.SmallIntegerField(default=0, verbose_name='Current Round')),
                ('numFinishedCurrentRound', models.SmallIntegerField(default=0, verbose_name='Number of players who have finished the current round')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('position', models.SmallIntegerField(verbose_name='Position')),
                ('wasCreator', models.BooleanField(verbose_name='Created game')),
                ('currentRound', models.SmallIntegerField(default=0, verbose_name='Current Round')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drawwrite.Game')),
            ],
        ),
        migrations.CreateModel(
            name='WriteLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Description')),
                ('linkPosition', models.SmallIntegerField(verbose_name='Link Position')),
                ('addedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drawwrite.Player')),
                ('chain', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='drawwrite.Chain')),
            ],
        ),
        migrations.AddField(
            model_name='drawlink',
            name='addedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drawwrite.Player'),
        ),
        migrations.AddField(
            model_name='drawlink',
            name='chain',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='drawwrite.Chain'),
        ),
        migrations.AddField(
            model_name='chain',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='drawwrite.Player'),
        ),
    ]
