# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-08 03:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drawwrite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawlink',
            name='chain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drawwrite.Chain'),
        ),
        migrations.AlterField(
            model_name='writelink',
            name='chain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drawwrite.Chain'),
        ),
    ]
