# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 03:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drawwrite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawlink',
            name='addedBy',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='drawwrite.Player'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='writelink',
            name='addedBy',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='drawwrite.Player'),
            preserve_default=False,
        ),
    ]
