# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-09 01:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drawwrite', '0003_auto_20170608_1653'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='player',
            unique_together=set([]),
        ),
    ]
